# Generated by Django 5.0.6 on 2024-06-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='client',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='clients',
            field=models.ManyToManyField(to='mailing.client', verbose_name='клиенты'),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(verbose_name='тело сообщения'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='periodicity',
            field=models.CharField(choices=[('daily', 'раз в день'), ('weekly', 'раз в неделю'), ('monthly', 'раз в месяц')], max_length=10, verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='status',
            field=models.CharField(choices=[('created', 'создана'), ('launched', 'запущена'), ('completed', 'завершена')], max_length=9, verbose_name='статус'),
        ),
    ]
