# Generated by Django 4.2 on 2024-10-20 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_product_options_product_is_published'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
